general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.local/share/wallpapers/macbook-neo-blush.jpg
    blur_passes = 3
    blur_size = 8
    brightness = 0.85
}

label {
    monitor =
    text = cmd[update:1000] date +%H:%M
    color = rgba(fff4faff)
    font_size = 82
    font_family = Inter Display
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(fff4faff)
    font_size = 20
    font_family = Inter
    position = 0, 30
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 56
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = rgba(fff4fa99)
    inner_color = rgba(fbe4ef66)
    font_color = rgba(442334ff)
    font_family = Inter
    fade_on_empty = false
    placeholder_text = <i>Enter password</i>
    check_color = rgba(d65b93ff)
    fail_color = rgba(c43e60ff)
    rounding = 28
    position = 0, -50
    halign = center
    valign = center
}
